version: '3.8'

services:
  app:
    build:
      context: ./dagster
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: tradeopser
      POSTGRES_PASSWORD: amogus
      POSTGRES_DB: tradeops
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3432:5432"