apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dagster
  template:
    metadata:
      labels:
        app: dagster
    spec:
      containers:
      - name: dagster
        image: orson88/tradeops:dagster
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dagster-service
spec:
  selector:
    app: dagster
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30002
  type: NodePort